# Generated by Django 6.0.2 on 2026-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefectLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("siniflar", models.JSONField()),
                ("aktif_hatalar", models.JSONField()),
                ("esik", models.FloatField()),
                ("kaynak", models.CharField(default="web", max_length=20)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
